(()=>{'use strict';
const Q=window.AOUT_QUESTIONS;const LETTERS=['A','B','C','D','E'];const CODE='aoutedu335';const EXAM_MS=100*60*1000;const STORE='aoutEduCpns2026StateV3';
const $=id=>document.getElementById(id);const views={access:$('accessView'),instruction:$('instructionView'),exam:$('examView'),result:$('resultView')};
let state=loadState();let filter='all',tick=null,toastTimer=null;
function blankState(){return{answers:{},marked:{},current:1,started:false,finished:false,endAt:null,startedAt:null,finishedAt:null,scores:null}}
function loadState(){try{return Object.assign(blankState(),JSON.parse(localStorage.getItem(STORE)||'{}'))}catch{return blankState()}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function showView(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle('hidden',k!==name));window.scrollTo(0,0)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function qById(id){return Q[id-1]}function sectionFor(id){return id<=30?'TWK':id<=65?'TIU':'TKP'}
function counts(){const answered=Object.keys(state.answers).filter(k=>state.answers[k]).length;const marked=Object.keys(state.marked).filter(k=>state.marked[k]).length;return{answered,unanswered:110-answered,marked}}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function authenticate(){if($('accessCode').value.trim()===CODE){sessionStorage.setItem('aoutAccess','1');$('accessError').textContent='';prepareInstruction()}else{$('accessError').textContent='Kode akses tidak sesuai. Periksa kembali.';$('accessCode').focus()}}
function prepareInstruction(){showView('instruction');const resumable=state.started&&!state.finished&&state.endAt>Date.now();$('resumeButton').classList.toggle('hidden',!resumable);$('startButton').classList.toggle('hidden',resumable)}
function startExam(){state=blankState();state.started=true;state.startedAt=Date.now();state.endAt=Date.now()+EXAM_MS;save();enterExam()}
function resumeExam(){if(!state.endAt||state.endAt<=Date.now()){finishExam(true);return}enterExam()}
function enterExam(){showView('exam');renderAll();startTimer()}
function startTimer(){clearInterval(tick);updateTimer();tick=setInterval(updateTimer,1000)}
function updateTimer(){const left=Math.max(0,(state.endAt||Date.now())-Date.now());const sec=Math.ceil(left/1000);$('timer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('timerBox').classList.toggle('warning',sec<=600&&sec>300);$('timerBox').classList.toggle('critical',sec<=300);if(left<=0){clearInterval(tick);finishExam(true)}}
function renderAll(){renderNumbers();renderQuestion();renderCounts()}
function renderCounts(){const c=counts();$('answeredCount').textContent=c.answered;$('unansweredCount').textContent=c.unanswered;$('markedCount').textContent=c.marked;$('answeredCompact').textContent=`${c.answered}/110 terjawab`;$('progressBar').style.width=`${c.answered/110*100}%`;$('drawerSummary').textContent=`${c.answered} terjawab · ${c.unanswered} kosong`}
function numberClass(id){return[state.answers[id]?'answered':'',state.marked[id]?'marked':'',state.current===id?'current':''].filter(Boolean).join(' ')}
function renderNumbers(){const strip=$('numberStrip');strip.innerHTML=Q.map(q=>`<button class="num-chip ${numberClass(q.id)}" data-go="${q.id}">${q.id}</button>`).join('');renderGrid();requestAnimationFrame(()=>strip.querySelector('.current')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}))}
function renderGrid(){const list=Q.filter(q=>filter==='all'||(filter==='answered'&&state.answers[q.id])||(filter==='unanswered'&&!state.answers[q.id])||(filter==='marked'&&state.marked[q.id]));$('questionGrid').innerHTML=list.map(q=>`<button class="grid-num ${numberClass(q.id)}" data-go="${q.id}">${q.id}</button>`).join('')}
function setCurrent(id){state.current=Math.max(1,Math.min(110,Number(id)));save();renderAll();if(innerWidth<821)closeDrawer()}
function renderQuestion(){const q=qById(state.current),section=sectionFor(q.id);$('sectionLabel').textContent=`${section} · No. ${q.id}`;const badge=$('sectionBadge');badge.textContent=section;badge.className=`section-badge ${section.toLowerCase()}`;$('prevButton').disabled=q.id===1;$('nextButton').textContent=q.id===110?'Tinjau & Selesai →':'Berikutnya →';$('markButton').classList.toggle('active',!!state.marked[q.id]);$('markButton').textContent=state.marked[q.id]?'★ Ditandai':'☆ Tandai';if(q.kind==='figural')renderFigural(q);else renderText(q)}
function renderText(q){$('questionStage').innerHTML=`<article class="question-card"><header class="question-head"><div class="question-no"><strong>${q.id}</strong><span>${q.section} · PILIH SATU JAWABAN</span></div><span class="status-pill">${state.answers[q.id]?'Terjawab':'Belum dijawab'}</span></header><div class="question-body"><p class="question-text">${escapeHtml(q.prompt)}</p><div class="options">${q.options.map((o,i)=>{const L=LETTERS[i];return`<button class="option ${state.answers[q.id]===L?'selected':''}" data-answer="${q.id}:${L}"><span class="option-letter">${L}</span><span class="option-text">${escapeHtml(o)}</span></button>`}).join('')}</div></div></article>`}
function renderFigural(q){const start=q.stimulus==='A'?31:37,end=q.stimulus==='A'?36:40,img=q.stimulus==='A'?'assets/gambar-a.jpeg':'assets/gambar-b.jpeg';let rows='';for(let id=start;id<=end;id++){rows+=`<div class="figural-row ${state.current===id?'current':''}"><strong>${id}</strong>${LETTERS.map(L=>`<button class="fig-choice ${state.answers[id]===L?'selected':''}" data-answer="${id}:${L}">${L}</button>`).join('')}</div>`}$('questionStage').innerHTML=`<article class="figural-card"><header class="question-head"><div class="question-no"><strong>${q.stimulus}</strong><span>GAMBAR ${q.stimulus} · SOAL ${start}–${end}</span></div><span class="status-pill">No. ${q.id}</span></header><div class="figural-layout"><div class="stimulus-pane"><img src="${img}" alt="Gambar ${q.stimulus} TIU Figural"><button class="zoom-btn" data-zoom="${img}">Perbesar gambar ↗</button></div><div class="answer-pane"><h2>Pilih jawaban</h2><p>Gambar stimulus hanya ditampilkan satu kali. Setiap nomor di bawah hanya berisi opsi A–E.</p>${rows}</div></div></article>`}
function answer(id,letter){state.answers[id]=letter;state.current=Number(id);save();renderAll()}
function toggleMark(){const id=state.current;state.marked[id]=!state.marked[id];if(!state.marked[id])delete state.marked[id];save();renderAll();toast(state.marked[id]?'Soal ditandai untuk ditinjau.':'Tanda soal dihapus.')}
function prev(){if(state.current>1)setCurrent(state.current-1)}function next(){if(state.current<110)setCurrent(state.current+1);else openFinish()}
function openFinish(){const c=counts();$('finishStats').innerHTML=`<div><strong>${c.answered}</strong><span>TERJAWAB</span></div><div><strong>${c.unanswered}</strong><span>KOSONG</span></div><div><strong>${c.marked}</strong><span>DITANDAI</span></div>`;$('finishModal').classList.remove('hidden')}
function closeFinish(){$('finishModal').classList.add('hidden')}
function score(){let twk=0,tiu=0,tkp=0;for(const q of Q){const a=state.answers[q.id];if(!a)continue;if(q.id<=30){if(a===q.answer)twk+=5}else if(q.id<=65){if(a===q.answer)tiu+=5}else tkp+=q.scores[a]||0}return{twk,tiu,tkp,total:twk+tiu+tkp}}
function finishExam(auto=false){clearInterval(tick);state.finished=true;state.finishedAt=Date.now();state.scores=score();save();closeFinish();showResults();if(auto)toast('Waktu habis. Jawaban dikumpulkan otomatis.')}
function showResults(){showView('result');const s=state.scores||score();$('scoreTwk').textContent=s.twk;$('scoreTiu').textContent=s.tiu;$('scoreTkp').textContent=s.tkp;$('scoreTotal').textContent=s.total}
function openDrawer(){$('drawer').classList.add('open');$('drawerBackdrop').classList.add('show')}function closeDrawer(){$('drawer').classList.remove('open');$('drawerBackdrop').classList.remove('show')}
function openZoom(src){$('zoomImage').src=src;$('imageModal').classList.remove('hidden')}
function whatsapp(){const s=state.scores||score();const msg=`Halo Kak Affie, saya telah menyelesaikan Simulasi SKD CPNS 2026 Aout Edu.\n\nHasil saya:\nTWK: ${s.twk}\nTIU: ${s.tiu}\nTKP: ${s.tkp}\nTotal: ${s.total}\n\nSaya sudah mengunduh PDF jawaban saya dan ingin mengetahui jawaban yang salah serta mendapatkan kunci jawaban dan pembahasan lengkap.`;window.open(`https://wa.me/6285173479651?text=${encodeURIComponent(msg)}`,'_blank','noopener')}
// Canvas-based, dependency-free PDF generator
function loadImage(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=src})}
function wrap(ctx,text,maxWidth){const words=String(text).split(/\s+/),lines=[];let line='';for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);return lines}
async function buildAnswerPdf(){const btn=$('downloadButton');const old=btn.textContent;btn.disabled=true;btn.textContent='Menyiapkan PDF…';try{const owie=await loadImage('assets/owie.png'),imgA=await loadImage('assets/gambar-a.jpeg'),imgB=await loadImage('assets/gambar-b.jpeg');const W=794,H=1123,M=54;let canvases=[];let canvas,ctx,y;
function newPage(title='JAWABAN SIMULASI SKD CPNS 2026'){canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;ctx=canvas.getContext('2d');ctx.fillStyle='#f4f8fb';ctx.fillRect(0,0,W,H);ctx.fillStyle='#0c2f5c';ctx.fillRect(0,0,W,88);ctx.fillStyle='#fff';ctx.font='700 20px Arial';ctx.fillText('AOUT EDU',M,36);ctx.font='700 16px Arial';ctx.fillText(title,M,63);ctx.drawImage(owie,W-108,10,62,62);y=118;canvases.push(canvas)}
function ensure(h){if(y+h>H-54)newPage()}
function text(t,x,w,font='14px Arial',color='#17233a',lh=20){ctx.font=font;ctx.fillStyle=color;const ls=wrap(ctx,t,w);ls.forEach(line=>{ctx.fillText(line,x,y);y+=lh});return ls.length*lh}
function qText(q){ensure(130);ctx.fillStyle='#0c2f5c';ctx.font='700 15px Arial';ctx.fillText(`${q.id}.`,M,y);const startY=y;text(q.prompt,M+28,W-M*2-28,'14px Arial','#17233a',20);y=Math.max(y,startY+20)+4;q.options.forEach((o,i)=>{ctx.fillStyle='#17233a';ctx.font='13px Arial';const ls=wrap(ctx,`${LETTERS[i]}. ${o}`,W-M*2-18);ls.forEach(line=>{ctx.fillText(line,M+18,y);y+=18})});ctx.fillStyle='#1fa8a5';ctx.font='700 13px Arial';ctx.fillText(`Jawaban peserta: ${state.answers[q.id]||'Belum dijawab'}`,M+18,y+5);y+=34;ctx.strokeStyle='#d9e4ec';ctx.beginPath();ctx.moveTo(M,y);ctx.lineTo(W-M,y);ctx.stroke();y+=18}
newPage('RINGKASAN HASIL');ctx.fillStyle='#0c2f5c';ctx.font='700 32px Arial';ctx.fillText('Jawaban Saya',M,y+20);y+=56;const s=state.scores||score();[['TWK',s.twk,150],['TIU',s.tiu,175],['TKP',s.tkp,225],['TOTAL',s.total,550]].forEach((a,i)=>{const x=M+(i%2)*340,yy=y+Math.floor(i/2)*100;ctx.fillStyle=i===3?'#0c2f5c':'#fff';ctx.strokeStyle='#d9e4ec';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(x,yy,310,78,14);ctx.fill();ctx.stroke();ctx.fillStyle=i===3?'#fff':'#68748a';ctx.font='700 12px Arial';ctx.fillText(a[0],x+18,yy+25);ctx.font='700 26px Arial';ctx.fillStyle=i===3?'#fff':'#0c2f5c';ctx.fillText(`${a[1]} / ${a[2]}`,x+18,yy+58)});y+=230;ctx.fillStyle='#17233a';ctx.font='14px Arial';['PDF ini hanya memuat soal dan jawaban peserta.','Tidak ada tanda benar/salah, kunci jawaban, ataupun pembahasan.','Tanggal: '+new Date(state.finishedAt||Date.now()).toLocaleString('id-ID')].forEach(t=>{ctx.fillText(t,M,y);y+=24});
for(const q of Q.filter(x=>x.id<=30))qText(q);
newPage('GAMBAR A — SOAL 31–36');const ar=imgA.width/imgA.height;let aw=W-M*2,ah=aw/ar;if(ah>780){ah=780;aw=ah*ar}ctx.drawImage(imgA,(W-aw)/2,y,aw,ah);y+=ah+24;ctx.font='700 15px Arial';ctx.fillStyle='#0c2f5c';for(let id=31;id<=36;id++){ctx.fillText(`${id}.  Jawaban peserta: ${state.answers[id]||'Belum dijawab'}`,M,y);y+=25}
newPage('GAMBAR B — SOAL 37–40');const br=imgB.width/imgB.height;let bw=W-M*2,bh=bw/br;if(bh>790){bh=790;bw=bh*br}ctx.drawImage(imgB,(W-bw)/2,y,bw,bh);y+=bh+24;ctx.font='700 15px Arial';ctx.fillStyle='#0c2f5c';for(let id=37;id<=40;id++){ctx.fillText(`${id}.  Jawaban peserta: ${state.answers[id]||'Belum dijawab'}`,M,y);y+=25}
for(const q of Q.filter(x=>x.id>=41))qText(q);
const jpgs=[];for(const c of canvases){const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.86));jpgs.push(new Uint8Array(await blob.arrayBuffer()))}const pdf=jpegPagesToPdf(jpgs,W,H);const blob=new Blob([pdf],{type:'application/pdf'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Jawaban_Simulasi_CPNS_2026_Aout_Edu.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);toast('PDF jawaban berhasil dibuat.')}catch(e){console.error(e);toast('PDF gagal dibuat. Coba ulangi pada browser terbaru.')}finally{btn.disabled=false;btn.textContent=old}}
function jpegPagesToPdf(images,pw,ph){const parts=[],offsets=[0];let pos=0;const add=v=>{const b=typeof v==='string'?new TextEncoder().encode(v):v;parts.push(b);pos+=b.length};add('%PDF-1.4\n%âãÏÓ\n');const n=images.length,objCount=2+n*3;const obj=(id,body)=>{offsets[id]=pos;add(`${id} 0 obj\n`);if(Array.isArray(body)){body.forEach(add)}else add(body);add('\nendobj\n')};obj(1,'<< /Type /Catalog /Pages 2 0 R >>');const kids=images.map((_,i)=>`${3+i*3} 0 R`).join(' ');obj(2,`<< /Type /Pages /Kids [${kids}] /Count ${n} >>`);images.forEach((img,i)=>{const pageId=3+i*3,imgId=pageId+1,contentId=pageId+2,name=`Im${i+1}`;obj(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /${name} ${imgId} 0 R >> >> /Contents ${contentId} 0 R >>`);obj(imgId,[`<< /Type /XObject /Subtype /Image /Width ${pw} /Height ${ph} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${img.length} >>\nstream\n`,img,'\nendstream']);const stream=`q\n595.28 0 0 841.89 0 0 cm\n/${name} Do\nQ`;obj(contentId,`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`)});const xref=pos;add(`xref\n0 ${objCount+1}\n0000000000 65535 f \n`);for(let i=1;i<=objCount;i++)add(`${String(offsets[i]||0).padStart(10,'0')} 00000 n \n`);add(`trailer\n<< /Size ${objCount+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const len=parts.reduce((a,b)=>a+b.length,0),out=new Uint8Array(len);let o=0;parts.forEach(p=>{out.set(p,o);o+=p.length});return out}
function reset(){if(!confirm('Hapus sesi ini dan mulai dari awal?'))return;localStorage.removeItem(STORE);state=blankState();showView('instruction');prepareInstruction();$('consent').checked=false;$('startButton').disabled=true}
// listeners
$('accessButton').onclick=authenticate;$('accessCode').addEventListener('keydown',e=>{if(e.key==='Enter')authenticate()});$('toggleCode').onclick=()=>{$('accessCode').type=$('accessCode').type==='password'?'text':'password'};$('consent').onchange=e=>$('startButton').disabled=!e.target.checked;$('startButton').onclick=startExam;$('resumeButton').onclick=resumeExam;$('prevButton').onclick=prev;$('nextButton').onclick=next;$('markButton').onclick=toggleMark;$('finishButton').onclick=openFinish;$('confirmFinish').onclick=()=>finishExam(false);document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=closeFinish);$('drawerButton').onclick=openDrawer;$('drawerClose').onclick=closeDrawer;$('drawerBackdrop').onclick=closeDrawer;$('stripLeft').onclick=()=>$('numberStrip').scrollBy({left:-320,behavior:'smooth'});$('stripRight').onclick=()=>$('numberStrip').scrollBy({left:320,behavior:'smooth'});$('imageModalClose').onclick=()=>$('imageModal').classList.add('hidden');$('imageModal').addEventListener('click',e=>{if(e.target===$('imageModal'))$('imageModal').classList.add('hidden')});$('whatsappButton').onclick=whatsapp;$('downloadButton').onclick=buildAnswerPdf;$('resetButton').onclick=reset;
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)setCurrent(go.dataset.go);const ans=e.target.closest('[data-answer]');if(ans){const[id,L]=ans.dataset.answer.split(':');answer(Number(id),L)}const z=e.target.closest('[data-zoom]');if(z)openZoom(z.dataset.zoom);const ft=e.target.closest('[data-filter]');if(ft){filter=ft.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===ft));renderGrid()}});
window.addEventListener('beforeunload',e=>{if(state.started&&!state.finished){e.preventDefault();e.returnValue=''}});
// initial route
if(sessionStorage.getItem('aoutAccess')==='1'){if(state.finished)showResults();else prepareInstruction()}else showView('access');
})();